import 'package:flutter/material.dart';

class AppColors {
  static const Color green = Color(0xFF22B14C);
  static const Color orange = Color(0xFFFF9900);
  static const Color purple = Color(0xFFB063FF);
  static const Color blueAccent = Color(0xFF3267FF);
  static const Color teal = Color(0xFF10B981);
  static const Color red = Color(0xFFE74C3C);
  static const Color blue = Color(0xFF0099FF);
  static const Color cardBorder = Color(0xFFE0E0E0);
  static const Color yellow = Color(0xFFFFF8E1);
  static const Color yellowDark = Color(0xFFFFC107);
  static const Color textDark = Color(0xFF222222);
  static const Color textLight = Color(0xFF757575);
  static const Color cardBg = Colors.white;
  static const Color white = Color(0xFFFFFFFF);
  static const Color bgWhite = Color(0xFFFFFFFF);
  static const Color black = Colors.black87;
  static const Color green600 = Color(0xFF43A047);
  static const Color grey = Colors.grey;
  static const Color liteGrey = Color(0xFFB5B6B8);
  static const Color bggrey = Color(0xFFE0E0E0);
  static const Color buttongrey = Color(0xB5B6B8FF);
  static const Color skyblue = Color(0xFF80D4FF);
  static const Color indigo900 = Color(0xFF1A237E);
  static const Color green800 = Color(0xFF2E7D32);
  static const Color verylightgreen = Color(0xFFE6F9E8);
  static const Color brightMintGreen = Color(0xFF60EF76);
  static const Color black12 = Colors.black12;
  static const Color black87 = Colors.black87;
  static const Color softPeachyOrange = Color(0xFFFED7A5);
  static const Color vibrantOrange = Color(0xFFF98200);
  static const Color transparentBlack = Color(0x11000000);
  static const Color grey400 = Color(0xFFBDBDBD);
  static const Color grey100 = Color(0xFFF5F5F5);
  static const Color lightGrey = Color(0xFFE0E0E0);
  static const Color lightBlue = Color(0xFFCCE7FF);
  static const Color mediumBlue = Color(0xFF5DBBFF);
  static const Color lightGreen = Color(0xFFDAFFDA);
  static const Color veryLightBlue = Color(0xFFE8EDFF);
  static const Color lightYellow = Color(0xFFFFF0D6);
  static const Color lightRed = Color(0xFFFFD6D6);
  static const Color lightPeach = Color(0xFFFFEACC);
  static const Color lightSkyBlue = Color(0xFFD6EEFF);
  static const Color primaryBlue = Color(0xFF2196F3);
  static const Color greenShade = Color(0xFF43A047);
  static const Color gold = Color(0xFFFFD700);

}
